### ISSUE TITLE
data unloadable when xml refers period overlapping nc files

### ISSUE THREAD

**Issue by lee1043** [durack1/CMIPLib#3]
A daily precipitation xml:
`/work/cmip5-test/new/historical/atmos/day/pr/cmip5.CanESM2.historical.r1i1p1.day.atmos.day.pr.10000.v20120410.xml`
 
which refers following 2 files:
`pr_day_CanESM2_historical_r1i1p1_18500101-20051231.nc`
`pr_day_CanESM2_historical_r1i1p1_19790101-20051231.nc`
in directory of:
`/p/css03/esgf_publish/cmip5/output1/CCCma/CanESM2/historical/day/atmos/day/r1i1p1/v20120410/pr`
 
The xml refers two netCDF files those have overlapping period. Because of that, when I load data for one year from overlapped period, as for example:
``` python
import cdms2, cdtime, os
xml_dir = '/work/cmip5-test/new/historical/atmos/day/pr'
xml_file = 'cmip5.CanESM2.historical.r1i1p1.day.atmos.day.pr.10000.v20120410.xml'
f = cdms2.open(os.path.join(xml_dir,xml_file))
year = 1979
d = f('pr', time=(cdtime.comptime(year), cdtime.comptime(year+1)))
```

It returns following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20180702/lib/python2.7/site-packages/cdms2/cudsinterface.py", line 34, in __call__
    return v(*args, **kwargs)
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20180702/lib/python2.7/site-packages/cdms2/avariable.py", line 194, in __call__
    grid=grid)
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20180702/lib/python2.7/site-packages/cdms2/selectors.py", line 187, in unmodified_select
    fetched = result.subRegion(*specifications)
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20180702/lib/python2.7/site-packages/cdms2/avariable.py", line 975, in subRegion
    return self.subSlice(*slicelist, **d)
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20180702/lib/python2.7/site-packages/cdms2/avariable.py", line 793, in subSlice
    id=self.id)
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20180702/lib/python2.7/site-packages/cdms2/tvariable.py", line 203, in __init__
    self.initDomain(axes, copyaxes=copyaxes)
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20180702/lib/python2.7/site-packages/cdms2/tvariable.py", line 361, in initDomain
    self.copyAxis(i, flataxes[i])
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20180702/lib/python2.7/site-packages/cdms2/tvariable.py", line 423, in copyAxis
    self.setAxis(n, mycopy)
  File "/export_backup/lee1043/anaconda2/envs/pmp_nightly_20180702/lib/python2.7/site-packages/cdms2/tvariable.py", line 399, in setAxis
    (len(axis), axislen))
cdms2.error.CDMSError: axis length 365 does not match corresponding dimension 730
```

**Comment by durack1** [comment]
@lee1043 thanks, and so we start our log of problems..

**Comment by durack1** [comment]
@doutriaux1 @dnadeau4 this seems to be a `cdscan` issue, as it seems that both files contain the same temporal range, and so cdscan should use the first series 185001-197812 from the first file, and append 197901-200512 from the second.
File 1:
```
> ncdump -ct /p/css03/esgf_publish/cmip5/output1/CCCma/CanESM2/historical/day/atmos/day/r1i1p1/v20120410/pr/pr_day_CanESM2_historical_r1i1p1_18500101-20051231.nc 
netcdf pr_day_CanESM2_historical_r1i1p1_18500101-20051231 {
dimensions:
	time = UNLIMITED ; // (56940 currently)
	lat = 64 ;
	lon = 128 ;
	bnds = 2 ;
variables:
...
		:experiment = "historical" ;
		:frequency = "day" ;
		:creation_date = "2011-04-13T23:04:41Z" ;
		:history = "2011-04-13T23:04:41Z CMOR rewrote data to comply with CF standards and CMIP5 requirements." ;
...
data:
 time = "1850-01-01 12", "1850-01-02 12", "1850-01-03 12", "1850-01-04 12", 
    "1850-01-05 12", "1850-01-06 12", "1850-01-07 12", "1850-01-08 12", 
    "1850-01-09 12", "1850-01-10 12", "1850-01-11 12", "1850-01-12 12",
...
    "2005-12-20 12", "2005-12-21 12", "2005-12-22 12", "2005-12-23 12", 
    "2005-12-24 12", "2005-12-25 12", "2005-12-26 12", "2005-12-27 12", 
    "2005-12-28 12", "2005-12-29 12", "2005-12-30 12", "2005-12-31 12" ;
```
File 2:
```
> ncdump -ct /p/css03/esgf_publish/cmip5/output1/CCCma/CanESM2/historical/day/atmos/day/r1i1p1/v20120410/pr/pr_day_CanESM2_historical_r1i1p1_19790101-20051231.nc 
netcdf pr_day_CanESM2_historical_r1i1p1_19790101-20051231 {
dimensions:
	time = UNLIMITED ; // (9855 currently)
	lat = 64 ;
	lon = 128 ;
	bnds = 2 ;
variables:
...
		:experiment = "historical" ;
		:frequency = "day" ;
		:creation_date = "2011-04-14T22:18:59Z" ;
		:history = "2011-04-14T22:18:59Z CMOR rewrote data to comply with CF standards and CMIP5 requirements." ;
...
data:
 time = "1979-01-01 12", "1979-01-02 12", "1979-01-03 12", "1979-01-04 12", 
    "1979-01-05 12", "1979-01-06 12", "1979-01-07 12", "1979-01-08 12", 
    "1979-01-09 12", "1979-01-10 12", "1979-01-11 12", "1979-01-12 12",
...
    "2005-12-21 12", "2005-12-22 12", "2005-12-23 12", "2005-12-24 12", 
    "2005-12-25 12", "2005-12-26 12", "2005-12-27 12", "2005-12-28 12", 
    "2005-12-29 12", "2005-12-30 12", "2005-12-31 12" ;
```
@lee1043, is the 1979-2005 data in both files identical?

ping @pochedls
